version: '3'
services:
    dockerangular-multistage-service:
      build:
        context: .
        dockerfile: Dockerfile
      environment:
        NODE_ENV: production
      ports:
        - 8080:80
