version: '3'
services:
    dockerangular-multistage-service:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/usr/app
        - /usr/app/node_modules
      environment:
        NODE_ENV: production
      ports:
        - 8081:80
